### PR TITLE
validate entity name uniqueness

### PR DESCRIPTION
**Pull request by jediU**

### CODE REVIEW

**Review by Don-PhDev — APPROVED** [review]
LGTM!, but there are several changes that is not related to the title. Also create another ticket for the other changes.

**Comment by rusbal** [comment]
Too many code changes for "validate entity name uniqueness"

Please close this.  Pull latest master.  Rebase your code.

**Review by rusbal — CHANGES_REQUESTED** [review]
Rejected.

**Comment by rusbal** [comment]
Only these two lines are relevant.

```
t.string :name, null: false, unique: true

validates :name, presence: true, uniqueness: true
```

**Pull request closed without merging**
